### ISSUE TITLE
关于openwrt上部署Phantun的问题

### ISSUE THREAD

**Issue by ibeange** [yabostone/blog.fengidea.com#2]
开发者你好，我通过搜索引擎搜索到你的博客，看到你有在openwrt上部署成功Phantun。由于我想在openwrt上使用wireguard和Phantun，所以想请教你部署Phantun的方法，感谢。

**Comment by yabostone** [comment]
如果没有大流量应用，建议使用udp2raw，phantun的配置较为复杂，我也只是命令行调试通过了，没有形成文档。
目前wireguard好像三大运营商屏蔽的不是很厉害，可以考虑直接连接。

**Comment by ibeange** [comment]
谢谢解惑，我目前的大流量场景主要是看远程下载的动漫以及看IPTV直播，习惯使用wireguard套一层连接，但是我看到有人提到如果UDP流量太高，运营商会限速，所以就在网上找到了Phantun，主要是看它的性能比较好。如果有机会，希望有机会拜读到你关于这个工具的使用文档。

**Comment by yabostone** [comment]
TCP一样会限速，，，有时间我试试，看看是不是UDP真的限速。有些时候国内两个点的直连实际上跑不满上传的带宽，我移动的上传100M，实际在下的时候只能跑到56Mbps的样子。

**Comment by ibeange** [comment]
我电信50M上传，但实际只有5-8M，有点慢的，所以我怀疑我被限速了，想试试使用phantun，但是没研究明白怎么在openwrt上使用。

**Comment by yabostone** [comment]
你可以先用udp2raw试试，50M情况udp2raw也能跑满的，而且流程上比这个简单的，确认是限速了再考虑phantun，这个需要添加tun，手动调试，而且debug文档稍微少些，调试复杂些。udp2raw在G口下影响不是很大的。

**Comment by ibeange** [comment]
好的，感谢，我先试试upd2raw。
