### ISSUE TITLE
关于picgo插件更新

### ISSUE THREAD

**Issue by W4J1e** [yabostone/blog.fengidea.com#3]
您好，很抱歉通过issue的方式打扰您。
最近发现 picgo-core 更新到了 1.5.0 以上版本，弃用了 request 改用 axios 。我尝试在本地修改并重新构建，但是每次上传图片 picgo 都会提示`TypeError: Cannot read properties of undefined (reading 'credentials')` 看起来好像是没有正确从多吉云的 api 获取到秘钥，这部分代码是您当时贡献的，加上这个插件本身是用 s3 插件改的，所以现在我无法解决这个问题。
如果您什么时候有时间，恳请指点一二，或者帮忙 PR ，感激不尽。

**Comment by yabostone** [comment]
额，是dogecloud的具体token获取改了么。我现在是网安公司，所以博客很少更新了。

**Comment by W4J1e** [comment]
> 额，是dogecloud的具体token获取改了么。我现在是网安公司，所以博客很少更新了。

新年快乐！
是 picgo-core 更新了，弃用了 request 改用 axios 。起初我只是按照 axios 的文档改了请求体，但是请求不到 token 。后来改好了我就关闭了这个 issue 。

**Comment by yabostone** [comment]
新年快乐！~~
那可能是token的请求方式不同，需要调试。
